[build]
builder = "NIXPACKS"

[phases.setup]
nixPkgs = [
  "php",
  "phpExtensions.pdo",
  "phpExtensions.pdo_mysql",
  "phpExtensions.mysqli",
  "phpExtensions.mbstring",
  "phpExtensions.curl",
  "composer"
]

[deploy]
start = "php -S 0.0.0.0:${PORT} -t public router.php"
